### ISSUE TITLE
review completed. 請重新練習。

### ISSUE THREAD

**Issue by hatelove** [cataska/TDDHomeworkDay1#1]
在測試案例中，只有看到 costs 的 array 以及 revenue 的 array, 我並沒有看到那 11 筆完整的資料（帶有 Cost, Revenue, SellPrice 描述的資料）

請重新練習後回覆 issue。

**Comment by cataska** [comment]
已重新練習。

**Comment by hatelove** [comment]
good. 建議如下：

1. class SumByGroup 可以改成 extension method 擴充 `IEnumerable<T>`, 在測試案例中使用，直接用 `products.Sum(size, p=>p.Cost)` 即可。
1. 在 C# 中，以這個 homework 為例，會建議你在測試案例中用 property 塞值，而不是 constructor 塞值，原因是語意上看起來更清晰清楚，測試案例更接近需求描述。例如：
```
                        var products = new List<Product>()
			{
				new Product() { Id=1 ,Cost=1 ,Revenue=11,SellPrice=21 },
				new Product() { Id=2 ,Cost=2 ,Revenue=12,SellPrice=22 },
				new Product() { Id=3 ,Cost=3 ,Revenue=13,SellPrice=23 },
				new Product() { Id=4 ,Cost=4 ,Revenue=14,SellPrice=24 },
				new Product() { Id=5 ,Cost=5 ,Revenue=15,SellPrice=25 },
				new Product() { Id=6 ,Cost=6 ,Revenue=16,SellPrice=26 },
				new Product() { Id=7 ,Cost=7 ,Revenue=17,SellPrice=27 },
				new Product() { Id=8 ,Cost=8 ,Revenue=18,SellPrice=28 },
				new Product() { Id=9 ,Cost=9 ,Revenue=19,SellPrice=29 },
				new Product() { Id=10,Cost=10,Revenue=20,SellPrice=30 },
				new Product() { Id=11,Cost=11,Revenue=21,SellPrice=31 }
			};
```

**Comment by hatelove** [comment]
## 結論
可以參考一下我的 sample code: https://gist.github.com/hatelove/f5a4c2591293828b637f#file-getsumbypagesize_v2-cs

重點 focus 在下列幾點：

1. 呼叫端怎麼呼叫最好用, 語意清楚, 參數夠少, intellisense輔助。
2. API 在需求異動時，能越穩定越好，代表支援有足夠的彈性。在面對重構時，也不會影響到呼叫端的使用，例如 property rename。
3. 測試案例要怎麼呈現，最像口語化的描述著呼叫端使用情境。包含怎麼寫語意最清楚，寫起來最快。

這個 homework 基本上有四種方式來實作，也考驗著對 C# 的熟悉程度。

1. 使用 enum, production code 以 if/else 來分辨
1. 使用 string + reflection 來動態決定使用哪一個 property 加總
1. 使用 delegate/lambda 針對 Product 型別來處理
1. 使用 generic 支援泛型，使用 extension method 針對所有集合都提供這樣的功能

**Comment by cataska** [comment]
非常感謝！
